### PR TITLE
Try improving Chorizo Previewer Controls and Move Builds to designated dirs for easy cleanup

### PR DESCRIPTION
**Pull request by Byterset**
Hi,
I have added some key controls to the previewer and adjusted it so that it felt (arguably) smoother to use.
Also I have adjusted most Makefiles so that all the build files will be created in a separate build directory which can than easily be cleaned up and ignored by git

### CODE REVIEW

**Comment by buu342** [comment]
Heyo, thanks for the PR. I'll take a look at it tomorrow.

Don't sweat about the CI failing, seems to be something weird going on with wxWidgets?

**Comment by Byterset** [comment]
No pressure! I have just been using these settings for a while now since I find chorizo and the whole sausage64 lib very nice and I thought maybe someone else could find these changes useful.
Regarding the CI I got most builds to work (forgot to change the build path in the azure yaml) but there is some wxWidgets error with windows.h on the windows build, not sure what that's about since I didn't touch that I think 😅

**Comment by buu342** [comment]
Everything seems ok besides one regression I've noticed. It's treating keyboard input like I'm typing (So if I press W, it moves forward for a tick, waits half a second, and then moves normally. Same thing that happens when you hold a key down in a text editor).

I also noticed you changed the project toolkit from v141_xp to v141. Any reason? We have users who use this application under Windows XP, hence the reason for the specific toolkit.

**Comment by buu342** [comment]
Yeah, looks like wxGetKeyState is the better solution for this: https://forums.wxwidgets.org/viewtopic.php?p=166445#p166445

Here's a video of the problem for a better illustration of what I meant:
https://github.com/buu342/N64-Sausage64/assets/9880691/48e47414-a825-4b6c-b444-9b7471fe69d2

**Comment by Byterset** [comment]
Thanks for taking time to test it!
1. Regarding the key event I'll look into that, I didn't even notice that but with the video it's quite clear
2. I'm not sure what happened with the vcxproj lol I'll just try reverting it once I have some time next week

**Comment by Byterset** [comment]
Ah I think I remember now why I chose to replace wxGetKeyState()..
image
Have you ever encountered this? I have compiled wxWidgets from source and running 'gtk-launch --version" shows version 3.24.33
Are you possibly using a version prior to 3.18 as indicated by the error message? I am no expert in using wxWidgets so maybe I am doing/getting something wrong :D

**Comment by Byterset** [comment]
sooo, even after testing for a while I could not get it to work without some kinds of Assertion Error (../src/unix/utilsx11.cpp(2631): assert ""Assert failure"" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used) this happened even when I installed wx from scratch in the same version & config that is used in the CI. Maybe it's some WSL issue? But from version 3.18 of GTK onwards it does actually seem to not be supported anymore from what I can see in the GNOME GTK Repo. _(maybe important to note that the wxGetKeyState for the Shift Key works without any issues on either version)_

So now I 'debounced' the key events so that the issue you showed in the video does not happen anymore even with the version compatible keyevent change. 
I also reverted the vcxproj, which made the CI happy again :)

Let me know what you think, I feel like the controls now feel a lot like other 3D Engines (e.g. Unity) which I personally like

**Comment by buu342** [comment]
Yep, all's good now.

I'm running GTK `3.24.38`, and my wxWidgets version is 3.2.2.1. The CI build is using 3.1.5, but I'm not sure of the GTK version.

Perhaps the issue is how your compiled wxWidgets? This is how I did it (and the CI build does as well, according to [https://github.com/buu342/N64-Sausage64/blob/master/azure-pipelines.yml](azure-pipelines.yml)):
```
../configure --with-opengl --disable-shared
```

**Comment by Byterset** [comment]
Just to test it I compiled it the exact same way as the CI, config flags and everything :D

I suppose **something** is wrong but I can't tell.

Since the functionality is not supported except for special keys (see earlier screenshot) from 3.18 onwards I would suggest to merge the change to support all versions potential users might want to use. You be the judge of that :)

**Comment by buu342** [comment]
Yeah weird. Either way, I'm happy with the changes as they are. Thank you!

**Comment by Byterset** [comment]
No need to apologize, the lib and surrounding tools have already saved me a bunch of time

Good luck with your thesis!

**Pull request merged**
